# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:

  build: 
    cmds:
      - env GOOS=linux GOARCH=arm GOARM=5 go build ./01-getting-started/main.go
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

