# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:

  build: 
    cmds:
      - env GOOS=linux GOARCH=arm GOARM=5 go build {{.CLI_ARGS}}

  transfer:
    cmds:
      - scp {{.CLI_ARGS}} ghost@192.168.0.107:~/

  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

